# Site settings
title: Baker School Action
email: sgriffen@mindspring.com
description: ''
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bakeraction.org" # the base hostname & protocol for your site
twitter_username:
github_username:  

# Build settings
markdown: kramdown

prose:
  rooturl: '_posts'
  siteurl: "http://bakeraction.org"
  media: 'assets'
