# Site settings
title: Baker School Action
email: sgriffen@mindspring.com
description: ''
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bakeraction.org" # the base hostname & protocol for your site
twitter_username:
github_username:  
permalink: none

# Build settings
markdown: kramdown

prose:
  rooturl: '_posts'
  siteurl: "http://bakeraction.org"
  media: 'assets'
  metadata:
    _posts:
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: ""
      - name: "category"
        field:
          element: "select"
          label: "Category"
          options:
            - name: "Options"
              value: "Options"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "This"
              value: "This"
            - name: "That"
              value: "That"
