# Site settings
title: Baker School Action
email: sgriffen@mindspring.com
description: ''
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bakeraction.org" # the base hostname & protocol for your site
twitter_username:
github_username:  

permalink: none

# destination:      ./_site
# source:           .

# Handling Reading
exclude:           ["templates", "Gemfile", "Gemfile.lock"]

# Build settings
markdown: kramdown

prose:
  rooturl: '_posts'
  siteurl: "http://bakeraction.org"
  media: 'assets'
  metadata:
    _posts:
      - name: "categories"
        field:
          element: "select"
          label: "Category"
          options:
            - name: "Options"
              value: "Options"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "This"
              value: "This"
            - name: "That"
              value: "That"
